// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/kozmetika-naturalna",

  metadata: {
    title: "Vodič za prirodnu kozmetiku | PerfuMaria das Ervas",
    description:
      "80 recepata za 100% prirodnu kozmetiku koje možete pripremiti kod kuće. Testirane i proverene formule za ličnu upotrebu ili za pokretanje biznisa.",
  },

  hero: {
    headlineLine1: "80 recepata za",
    headlineHighlight: "PRIRODNU KOZMETIKU",
    subheadline:
      "Dobijte pristup tajnim receptima za 100% prirodnu kozmetiku koju možete napraviti u udobnosti svog doma! Testirane i proverene formule za ličnu upotrebu ili za pokretanje sopstvenog biznisa.",
    cta: "ŽELIM PRISTUP ODMAH!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minuti",
      seconds: "Sekunde",
    },
  },

  story: {
    text: "Sada ću vam dati jedan praktičan vodič, direktan, bez nepotrebnih komplikacija, ali izuzetno pouzdan, kako biste pravili svoju 100% prirodnu kozmetiku kod kuće. Bez trošenja bogatstva, bez zavisnosti od hiljada sastojaka – i sa mogućnošću da je koristite za sebe, poklanjate najmilijima ili čak prodajete, ukoliko želite da stvorite novi izvor prihoda!",
    imageAlt: "Prirodna kozmetika",
  },

  recipeList: {
    headline: "Upoznajte se sa",
    headlineHighlight: "80 recepata,",
    headlineSuffix: "kojima ćete dobiti pristup u Vodiču za prirodnu kozmetiku:",
    cta: "ŽELIM IH!",
    col1: [
      "Umirujuća krema za telo",
      "Krema za telo sa pantenolom",
      "Osvežavajući losion za telo",
      "Krema-sufle za telo",
      "Puter za telo sa urukumom",
      "Čvrsti puter za telo",
      "Ulje za telo",
      "Terapeutsko ulje za fleke i strije",
      "Dvofazno ulje za telo",
      "Prirodni losion za preplanuli ten",
      "Tečni sapun za telo",
      "Gel za tuširanje",
      "Čvrsti sapun za telo sa SCI",
      "Tradicionalni čvrsti sapun za telo",
      "Kremasti hidratantni sapun",
      "Piling sapun za telo (Soap Body Scrub)",
      "Piling za telo",
      "Piling za telo sa bademovim brašnom",
      "Prirodni iluminator za telo",
      "Sprej za telo (Body Splash)",
      "Krema za lice sa vitaminom C",
      "Krema za lice posle sunčanja sa lavandom",
      "Krema za lice sa glinom",
      "Hidratantni losion za lice sa jasminom",
      "Suvo ulje za lice (Dry Oil)",
      "Tečni sapun za lice",
      "Pena za čišćenje lica",
      "Serum za lice za suvu i osetljivu kožu",
      "Serum za lice za masnu kožu",
      "Serum za područje oko očiju",
      "Tonik za lice za suvu i osetljivu kožu",
      "Osvežavajući tonik za lice za masnu kožu",
      "Ulje za skidanje šminke (Cleansing Oil)",
      "Balzam za čišćenje lica (Cleansing Balm)",
      "Sapun sa crvenom glinom – Detoks i revitalizacija",
      "Nežni piling za lice",
      "Gel za lice sa salicilnom kiselinom",
      "Gel maska za lice sa hijaluronskom kiselinom",
      "Eliksir za lice od ruža",
      "Sprej za lice sa aloe verom",
      "Maska za kovrdžavu i talasastu kosu",
    ],
    col2: [
      "Maska za pravu i blago talasastu kosu",
      "Kremasti balzam",
      "Čvrsti balzam za kovrdžavu i talasastu kosu",
      "Čvrsti balzam za blago talasastu i pravu kosu",
      "Čvrsti šampon za kovrdžavu i talasastu kosu",
      "Čvrsti šampon za pravu i blago talasastu kosu",
      "Tečni šampon",
      "Kremasti šampon 2 u 1",
      "Dečiji šampon",
      "Balzam koji se ne ispira (Leave-In)",
      "Sprej za zaštitu kose od toplote",
      "Ulje za kosu",
      "Gel za kosu",
      "Prirodna pomada za kosu",
      "Hidratantni završni sprej",
      "Piling za skalp",
      "Tonik za rast kose",
      "Serum za rascvetale krajeve",
      "Parfem za kosu",
      "Prirodni sapun za intimnu negu",
      "Prirodni dečiji sapun za telo",
      "Prirodni tečni parfem",
      "Prirodni čvrsti parfem",
      "Pasta za zube u obliku gela",
      "Vodica za usta",
      "Dezodorans u spreju",
      "Melem od nevena",
      "Melem od arnike",
      "Hranljivi balzam za usne",
      "Prirodni karmin",
      "Prirodni piling za usne",
      "Sprej za skidanje šminke",
      "Pena za brijanje",
      "Prirodni losion posle brijanja",
      "Krema za ruke i stopala",
      "Gel za fiksiranje obrva",
      "Prirodna sveća za masažu",
      "Hranljivi serum za nokte i zanoktice",
      "Prirodni repelent",
      "Revitalizujuće soli za kupanje",
    ],
  },

  whatYouGet: {
    headline: "ŠTA ĆETE PRONAĆI U OVOM SAVRŠENOM VODIČU?",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Šta ćete pronaći u vodiču",
    items: [
      "Preko 80 testiranih i proverenih recepata – uključujući kremasti piling sapun, suvo ulje za lice, sprej za telo, termičku zaštitu za kosu i razne nove formule.",
      "Baze za kreme, gelove, šampone i sapune – naučite da pravite bezbedne i personalizovane formule za svaki tip kože i kose.",
      "Kompletan vodič korak po korak za početnike i napredne – savladajte sve, od osnovnih koncepata do najsloženijih tehnika.",
      "Katalog sastojaka – otkrijte prednosti različitih prirodnih sirovina kako biste pravili visokokvalitetnu kozmetiku.",
      "Fitoterapija primenjena u kozmetologiji – kako koristiti lekovite biljke da pojačate dejstvo svoje kozmetike.",
      "Tajne prirodnog formulisanja – regulacija pH vrednosti, konzerviranje, izbor sirovina i efikasne kombinacije.",
      "Saveti za kućnu i profesionalnu proizvodnju – napravite sopstveni atelje za prirodnu kozmetiku i usavršite svoje tehnike.",
      "Održivost i briga o životnoj sredini – naučite da pravite biorazgradivu i ekološku kozmetiku.",
    ],
  },

  testimonials: {
    headline: "POGLEDAJTE ŠTA LJUDI KAŽU O VODIČU ZA PRIRODNU KOZMETIKU:",
    cta: "ŽELIM PRISTUP ODMAH!",
    cards: [
      {
        name: "Marija S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Obožavam ovaj vodič! Već sam napravila umirujuću kremu za telo i sapun za lice, ispali su neverovatno. Mnogo su bolji od industrijskih proizvoda koje sam ranije koristila. Toplo preporučujem!",
        source: "WhatsApp",
      },
      {
        name: "Jelena G.",
        initials: "JG",
        color: "#0f766e",
        stars: 5,
        text: "Ljudi, kakav divan vodič! Recepti su veoma detaljni i laki za praćenje. Već sam prodala nekoliko proizvoda prijateljicama i one ih obožavaju. Vredi svake pare!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Plašila sam se da ga kupim, ali se definitivno isplatilo! Katalog sirovina mi je mnogo pomogao da razumem sastojke. Već sam napravila 6 različitih recepata i svi su ispali odlično.",
        source: "WhatsApp",
      },
      {
        name: "Jovana M.",
        initials: "JM",
        color: "#b45309",
        stars: 5,
        text: "Kakva neverovatna investicija! Uz vodič sam naučila da pravim čvrsti šampon i balzam. Kosa mi je mnogo zdravija i svakog meseca uštedim dosta novca. Hvala vam!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Sa Vodičem za prirodnu kozmetiku naučićete da pravite svoju kozmetiku od nule.",
    text2: "Pokazaće vam korak po korak kako da birate prirodne sastojke, prilagođavate formule različitim tipovima kože i kose i personalizujete proizvode prema svojim potrebama.",
    text3: "Osim toga, steći ćete samopouzdanje i samostalnost u formulisanju, jer ćete moći da testirate i prilagođavate recepte kako biste stvorili jedinstvene proizvode sa sopstvenim identitetom. Zahvaljujući detaljnom katalogu prirodnih sirovina, upoznaćete najbolje sastojke i naučiti idealne kombinacije za svaki kozmetički proizvod.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Samostalnost u prirodnoj kozmetici",
  },

  benefitsList: {
    headline: "Nezavisnost i kreativnost u prirodnoj kozmetici!",
    cta: "ŽELIM PRISTUP ODMAH!",
    items: [
      {
        bold: "Naučite da pravite",
        rest: " kreme, serume, šampone, sapune i mnogo toga drugog.",
      },
      {
        bold: "Otkrijte kako da birate",
        rest: " prave sastojke za svaku potrebu.",
      },
      {
        bold: "Postanite nezavisni od industrijske kozmetike i",
        rest: " razvijte personalizovane formule.",
      },
      {
        bold: "Uronite u fitoterapiju primenjenu u kozmetologiji,",
        rest: " koristeći terapeutska svojstva lekovitih biljaka.",
      },
      {
        bold: "Smanjite troškove",
        rest: " praveći sopstvenu kozmetiku, bez kompromisa po pitanju kvaliteta.",
      },
      {
        bold: "Dobijte pristup profesionalnim formulama",
        rest: " i naučite da bezbedno pravite najbolje proizvode.",
      },
      {
        bold: "Istaknite se na tržištu prirodne lepote,",
        rest: " koje sve više raste i ceni održive proizvode.",
      },
      {
        bold: "Naučite da napravite kućni kozmetički atelje,",
        rest: " uz praktične savete za organizaciju radnog prostora.",
      },
    ],
  },

  economy: {
    headline: "Ušteda i poslovna prilika na tržištu prirodne kozmetike!",
    text1: "Pravljenje sopstvene prirodne kozmetike je odlična prilika kako za uštedu, tako i za biznis. Uz Vodič za prirodnu kozmetiku naučićete da proizvodite visokokvalitetnu kozmetiku po niskoj ceni, izbegavajući previsoke troškove konvencionalnih proizvoda i investirajući u pristupačne i efikasne prirodne sastojke.",
    text2: "Ako želite da pokrenete svoj biznis, ovo je dragocen vodič za stvaranje održivog i unosnog preduzeća. Uz ekskluzivne formule i praktične savete o konzerviranju, pakovanju i tržištu, možete stvoriti sopstveni brend prirodne kozmetike, nudeći ručno rađene proizvode koji prate trend svesne i ekološke potrošnje.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Biznis na tržištu prirodne kozmetike",
  },

  finalCta: {
    urgencyLabel: "POSLEDNJI DAN ZA PORUČIVANJE",
    urgencySub: "po promotivnoj ceni!",
    urgencyText:
      "Ovo je vaša poslednja šansa da iskoristite našu specijalnu ponudu i postanete deo naše porodice sa hiljadama zadovoljnih polaznica!",
    offerPrice: "990 din",
    button: "PREUZMITE PRISTUP ODMAH!",
    productTitle: "Vodič za prirodnu kozmetiku!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    bundleList: [
      "80 recepata za prirodnu kozmetiku",
      "Kompletan edukativni materijal",
      "Edukativni katalog sirovina",
      "Zajednica polaznica",
      "Specijalizovana podrška za pitanja",
      "Spisak dobavljača",
    ],
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minuti",
      seconds: "Sekunde",
    },
  },

  footer: {
    tagline: "Otkrijte kako da napravite savršenu prirodnu kozmetiku!",
    linkLabel: "Kompletan kurs o prirodnoj kozmetici",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};