// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/prirodnakozmetika",

  metadata: {
    title: "Vodič za prirodnu kozmetiku",
    description:
      "80 recepata za 100% prirodnu kozmetiku koje možete pripremiti kod kuće. Testirane i proverene formule za bezbednu negu kože i izbegavanje toksičnih hemikalija.",
  },

  hero: {
    headlineLine1: "80 recepata za",
    headlineHighlight: "PRIRODNU KOZMETIKU",
    subheadline:
      "Dobijte pristup tajnim receptima za 100% prirodnu kozmetiku koju možete napraviti u udobnosti svog doma! Testirane i bezbedne formule da zaštitite svoju porodicu i oslobodite se industrijskih proizvoda punih toksina.",
    cta: "ŽELIM PRISTUP ODMAH!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minuti",
      seconds: "Sekunde",
    },
  },

  story: {
    text: "Sada ću vam dati jedan praktičan vodič, direktan, bez nepotrebnih komplikacija, ali izuzetno pouzdan, kako biste pravili svoju 100% prirodnu kozmetiku kod kuće. Bez trošenja bogatstva, bez zavisnosti od hiljada sastojaka – i sa radošću da je pravite za sebe, poklanjate najmilijima i da svi zajedno uživate u zdravoj i 100% bezbednoj nezi!",
    imageAlt: "Prirodna kozmetika",
  },

  recipeList: {
    headline: "Upoznajte se sa",
    headlineHighlight: "80 recepata,",
    headlineSuffix: "kojima ćete dobiti pristup u Vodiču za prirodnu kozmetiku:",
    cta: "ŽELIM IH!",
    col1: [
      "Umirujuća krema za telo",
      "Krema za telo sa pantenolom",
      "Osvežavajući losion za telo",
      "Krema-sufle za telo",
      "Puter za telo sa urukumom",
      "Čvrsti puter za telo",
      "Ulje za telo",
      "Terapeutsko ulje za fleke i strije",
      "Dvofazno ulje za telo",
      "Prirodni losion za preplanuli ten",
      "Tečni sapun za telo",
      "Gel za tuširanje",
      "Čvrsti sapun za telo sa SCI",
      "Tradicionalni čvrsti sapun za telo",
      "Kremasti hidratantni sapun",
      "Piling sapun za telo (Soap Body Scrub)",
      "Piling za telo",
      "Piling za telo sa bademovim brašnom",
      "Prirodni iluminator za telo",
      "Sprej za telo (Body Splash)",
      "Krema za lice sa vitaminom C",
      "Krema za lice posle sunčanja sa lavandom",
      "Krema za lice sa glinom",
      "Hidratantni losion za lice sa jasminom",
      "Suvo ulje za lice (Dry Oil)",
      "Tečni sapun za lice",
      "Pena za čišćenje lica",
      "Serum za lice za suvu i osetljivu kožu",
      "Serum za lice za masnu kožu",
      "Serum za područje oko očiju",
      "Tonik za lice za suvu i osetljivu kožu",
      "Osvežavajući tonik za lice za masnu kožu",
      "Ulje za skidanje šminke (Cleansing Oil)",
      "Balzam za čišćenje lica (Cleansing Balm)",
      "Sapun sa crvenom glinom – Detoks i revitalizacija",
      "Nežni piling za lice",
      "Gel za lice sa salicilnom kiselinom",
      "Gel maska za lice sa hijaluronskom kiselinom",
      "Eliksir za lice od ruža",
      "Sprej za lice sa aloe verom",
      "Maska za kovrdžavu i talasastu kosu",
    ],
    col2: [
      "Maska za pravu i blago talasastu kosu",
      "Kremasti balzam",
      "Čvrsti balzam za kovrdžavu i talasastu kosu",
      "Čvrsti balzam za blago talasastu i pravu kosu",
      "Čvrsti šampon za kovrdžavu i talasastu kosu",
      "Čvrsti šampon za pravu i blago talasastu kosu",
      "Tečni šampon",
      "Kremasti šampon 2 u 1",
      "Dečiji šampon",
      "Balzam koji se ne ispira (Leave-In)",
      "Sprej za zaštitu kose od toplote",
      "Ulje za kosu",
      "Gel za kosu",
      "Prirodna pomada za kosu",
      "Hidratantni završni sprej",
      "Piling za skalp",
      "Tonik za rast kose",
      "Serum za rascvetale krajeve",
      "Parfem za kosu",
      "Prirodni sapun za intimnu negu",
      "Prirodni dečiji sapun za telo",
      "Prirodni tečni parfem",
      "Prirodni čvrsti parfem",
      "Pasta za zube u obliku gela",
      "Vodica za usta",
      "Dezodorans u spreju",
      "Melem od nevena",
      "Melem od arnike",
      "Hranljivi balzam za usne",
      "Prirodni karmin",
      "Prirodni piling za usne",
      "Sprej za skidanje šminke",
      "Pena za brijanje",
      "Prirodni losion posle brijanja",
      "Krema za ruke i stopala",
      "Gel za fiksiranje obrva",
      "Prirodna sveća za masažu",
      "Hranljivi serum za nokte i zanoktice",
      "Prirodni repelent",
      "Revitalizujuće soli za kupanje",
    ],
  },

  whatYouGet: {
    headline: "ŠTA ĆETE PRONAĆI U OVOM IZVANREDNOM VODIČU?",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Šta ćete pronaći u vodiču",
    items: [
      "Preko 80 testiranih i proverenih recepata – uključujući kremasti piling sapun, suvo ulje za lice, sprej za telo, termičku zaštitu za kosu i razne nove inovativne formule.",
      "Baze za kreme, gelove, šampone i sapune – naučite da pravite potpuno bezbedne i personalizovane formule za svaki tip kože i kose.",
      "Kompletan vodič korak po korak za početnike i napredne – savladajte sve, od osnovnih koncepata do najsloženijih kozmetičkih tehnika.",
      "Katalog sastojaka – otkrijte prednosti različitih prirodnih sirovina kako biste pravili visokokvalitetnu i čistu kozmetiku.",
      "Fitoterapija primenjena u kozmetologiji – kako da maksimalno iskoristite lekovite biljke da pojačate dejstvo svoje kozmetike.",
      "Tajne prirodnog formulisanja – regulacija pH vrednosti, prirodno konzerviranje, izbor sirovina i najefikasnije sinergije.",
      "Saveti za savršenu kućnu proizvodnju – pretvorite svoju kuhinju u bezbedno mesto za stvaranje čiste kozmetike i usavršite svoje tehnike.",
      "Održivost i briga o životnoj sredini – naučite da pravite potpuno biorazgradivu kozmetiku prijateljsku prema planeti.",
    ],
  },

  testimonials: {
    headline: "POGLEDAJTE ŠTA KAŽU ŽENE KOJE VEĆ KORISTE VODIČ:",
    cta: "ŽELIM PRISTUP ODMAH!",
    cards: [
      {
        name: "Marija S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Obožavam ovaj vodič! Već sam napravila umirujuću kremu za telo i sapun za lice, ispali su neverovatno. Mnogo su bolji od industrijskih proizvoda koje sam ranije koristila. Toplo preporučujem svima!",
        source: "WhatsApp",
      },
      {
        name: "Jelena G.",
        initials: "JG",
        color: "#0f766e",
        stars: 5,
        text: "Devojke, kakav divan vodič! Recepti su veoma detaljni i laki za praćenje. Već sam napravila nekoliko proizvoda za prijateljice i one ih obožavaju. Vredi svake pare!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Plašila sam se da ga kupim, ali se definitivno isplatilo! Katalog sirovina mi je mnogo pomogao da razumem sastojke. Već sam napravila 6 različitih recepata i svi su ispali savršeno.",
        source: "WhatsApp",
      },
      {
        name: "Jovana M.",
        initials: "JM",
        color: "#b45309",
        stars: 5,
        text: "Kakva neverovatna investicija! Uz vodič sam konačno naučila da pravim čvrsti šampon i balzam. Kosa mi je oživela, mnogo je zdravija, a svakog meseca uštedim dosta novca na kozmetici. Hvala vam!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Sa Vodičem za prirodnu kozmetiku naučićete da pravite svoje proizvode potpuno od nule.",
    text2: "Pokazaće vam korak po korak kako da svesno birate prirodne sastojke, prilagođavate formule različitim tipovima kože i kose i personalizujete proizvode tako da savršeno odgovaraju vašim potrebama.",
    text3: "Steći ćete samopouzdanje i potpunu samostalnost u formulisanju. Moći ćete da testirate i usavršavate recepte, stvarajući jedinstvenu kozmetiku sa sopstvenim karakterom. Zahvaljujući detaljnom katalogu prirodnih sirovina, upoznaćete najbolje sastojke i otkriti idealne kombinacije za svaki tip proizvoda.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Samostalnost u pravljenju prirodne kozmetike",
  },

  benefitsList: {
    headline: "Nezavisnost i kreativnost u svetu prirodne nege!",
    cta: "ŽELIM PRISTUP ODMAH!",
    items: [
      {
        bold: "Naučite da pravite",
        rest: " kreme, serume, šampone, sapune i mnoge druge proizvode za negu.",
      },
      {
        bold: "Otkrijte kako da bez greške birate",
        rest: " prave sastojke za svaku specifičnu potrebu kože i kose.",
      },
      {
        bold: "Oslobodite se industrijske hemije i",
        rest: " razvijte 100% personalizovane, prirodne formule.",
      },
      {
        bold: "Uronite u fitoterapiju primenjenu u kozmetologiji,",
        rest: " crpeći puna šaka lekovita svojstva biljaka i ekstrakata.",
      },
      {
        bold: "Značajno smanjite svoje troškove",
        rest: " praveći sopstvenu kozmetiku, a da pritom ne žrtvujete njen kvalitet.",
      },
      {
        bold: "Dobijte pristup profesionalnim formulama",
        rest: " i naučite da bezbedno pravite proizvode najvišeg kvaliteta.",
      },
      {
        bold: "Pružite svojoj koži najbolju negu,",
        rest: " znajući tačno koje čiste sastojke koristite.",
      },
      {
        bold: "Zaštitite zdravlje svoje porodice",
        rest: " proizvodima bez štetnih konzervanasa i veštačkih boja.",
      },
    ],
  },

  economy: {
    headline: "Ušteda i zdrava nega bez ijednog grama hemije!",
    text1: "Pravljenje sopstvene prirodne kozmetike je najbolji način da zaštitite svoju kožu, a da istovremeno uštedite ogromne količine novca. Uz Vodič za prirodnu kozmetiku naučićete da proizvodite visokokvalitetne proizvode za delić cene onih iz drogerija. Tako ćete izbeći preplaćivanje komercijalne kozmetike pune hemije, investirajući u pristupačne, čiste i visoko efikasne prirodne sirovine.",
    text2: "Ovo je vaš neprocenjivi priručnik za prelazak na zdraviji stil života. Zahvaljujući ekskluzivnim receptima, povratićete potpunu kontrolu nad tim šta stavljate na svoje telo. Možete uživati u ručno rađenim proizvodima koji su 100% bezbedni, ekološki i blagi kako za vašu kožu, tako i za životnu sredinu.",
    cta: "POČINJEM DA PRAVIM!",
    imageAlt: "Zdrava nega",
  },

  finalCta: {
    urgencyLabel: "POSLEDNJI DAN ZA PORUČIVANJE",
    urgencySub: "po promotivnoj akcijskoj ceni!",
    urgencyText:
      "Ovo je vaša apsolutno poslednja šansa da iskoristite našu izuzetnu ponudu i pridružite se grupi hiljada oduševljenih polaznica!",
    offerPrice: "990 din",
    button: "PREUZMITE PRISTUP ODMAH!",
    productTitle: "Vodič za prirodnu kozmetiku!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    bundleList: [
      "80 recepata za prirodnu kozmetiku",
      "Sveobuhvatni vodič korak po korak",
      "Edukativni leksikon sirovina",
      "Pristup zatvorenoj zajednici",
      "Podrška stručnjaka za sva pitanja",
      "Proveren i pouzdan spisak dobavljača",
    ],
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minuti",
      seconds: "Sekunde",
    },
  },

  footer: {
    tagline: "Otkrijte sa nama kako da napravite savršenu prirodnu kozmetiku!",
  },
};